name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      TF_VAR_REGION: ${{secrets.TF_VAR_REGION}}
      TF_VAR_IAM_USER_NAME: ${{secrets.TF_VAR_IAM_USER_NAME}}
      TF_VAR_BUCKET_NAME: ${{secrets.TF_VAR_BUCKET_NAME}}

    defaults:
      run:
        working-directory: ./terraform 

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run:  terraform fmt

      - name: Terraform INIT
        run:  terraform init

      - name: Terraform validate
        run:  terraform validate    
       
      - name: Terraform plan
        run:  terraform plan

      - name: Terrraform Apply
        run: terraform apply -auto-approve